# =====================================================
# Redis Docker Compose Configuration
# For local development and testing
# =====================================================

version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: lighting-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - lighting-app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: lighting-app-redis-ui
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:${REDIS_PASSWORD}
      - HTTP_USER=admin
      - HTTP_PASSWORD=${REDIS_PASSWORD}
    networks:
      - lighting-app-network
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local

networks:
  lighting-app-network:
    driver: bridge